import 'package:uuid/uuid.dart';
import '../models/application_model.dart';
import '../models/status_history_model.dart';
import '../models/document_model.dart';
import '../models/scholarship_model.dart';
import '../models/contact_model.dart';
import '../models/email_account_model.dart';
import '../repositories/application_repository.dart';

class SampleDataService {
  static Future<void> populateSampleData(ApplicationRepository repository) async {
    const uuid = Uuid();
    final now = DateTime.now();

    // Default Email Accounts
    final email1 = EmailAccountModel(
      id: uuid.v4(),
      emailAddress: 'student.academic@gmail.com',
      type: 'Personal',
      notes: 'Primary email used for European applications',
    );
    final email2 = EmailAccountModel(
      id: uuid.v4(),
      emailAddress: 'alex.scholar@university.edu',
      type: 'University',
      notes: 'Official undergraduate university email',
    );
    await repository.saveEmails([email1, email2]);

    // Application 1: Technical University of Munich (Current)
    final appId1 = uuid.v4();
    final app1 = ApplicationModel(
      id: appId1,
      universityName: 'Technical University of Munich',
      country: 'Germany',
      city: 'Munich',
      universityWebsite: 'https://www.tum.de',
      courseName: 'M.Sc. Informatics',
      degreeLevel: "Master's",
      faculty: 'Department of Computer Science',
      programWebsite: 'https://www.in.tum.de/en/informatics',
      studyMode: 'On Campus',
      duration: '2 Years',
      credits: '120 ECTS',
      language: 'English',
      intake: 'Winter',
      semesterYear: '2026',
      applicationDeadline: DateTime(now.year, now.month + 1, 15).toIso8601String().substring(0, 10),
      startOfApplications: DateTime(now.year, now.month - 1, 1).toIso8601String().substring(0, 10),
      scholarshipDeadline: DateTime(now.year, now.month + 1, 1).toIso8601String().substring(0, 10),
      housingDeadline: DateTime(now.year, now.month + 2, 1).toIso8601String().substring(0, 10),
      visaDeadline: DateTime(now.year, now.month + 3, 1).toIso8601String().substring(0, 10),
      decisionDate: DateTime(now.year, now.month + 2, 15).toIso8601String().substring(0, 10),
      applicationDate: DateTime(now.year, now.month - 1, 10).toIso8601String().substring(0, 10),
      status: 'Under Review',
      priority: 'High',
      applicationEmail: email1.emailAddress,
      isFavorite: true,
      applicationFee: 75.0,
      tuitionFee: 0.0, // No tuition in Bavaria for consecutive, standard semester fee
      livingCost: 11000.0,
      scholarshipAmount: 3600.0,
      ieltsRequired: true,
      ieltsOverallRequired: 6.5,
      ieltsListeningRequired: 6.0,
      ieltsReadingRequired: 6.0,
      ieltsWritingRequired: 6.0,
      ieltsSpeakingRequired: 6.0,
      myIeltsScore: 7.5,
      ieltsStatus: 'Requirement Met',
      gpaRequired: 3.2,
      myGpa: 3.75,
      sopRequired: true,
      cvRequired: true,
      recommendationRequired: true,
      interviewRequired: false,
      universityRating: 4.8,
      academicRating: 4.9,
      costRating: 4.7,
      locationRating: 4.5,
      careerRating: 4.8,
      studentLifeRating: 4.4,
      pros: 'Top-tier tech research, strong industry ties with BMW/Siemens, zero tuition fees.',
      cons: 'Competitive housing market in Munich, demanding coursework.',
      personalReview: 'Top priority choice in Europe with fantastic AI and systems labs.',
      generalNotes: 'Submitted via TUMonline and uni-assist VPD completed on time.',
      createdDate: DateTime.now().toIso8601String().substring(0, 10),
      lastUpdated: DateTime.now().toIso8601String().substring(0, 10),
    );

    // Application 2: Technical University of Munich (Previous Intake - rejected)
    final appId2 = uuid.v4();
    final app2 = ApplicationModel(
      id: appId2,
      universityName: 'Technical University of Munich',
      country: 'Germany',
      city: 'Munich',
      universityWebsite: 'https://www.tum.de',
      courseName: 'M.Sc. Informatics',
      degreeLevel: "Master's",
      faculty: 'Department of Computer Science',
      intake: 'Winter',
      semesterYear: '2025',
      applicationDeadline: '2025-05-31',
      startOfApplications: '2025-01-15',
      applicationDate: '2025-05-20',
      status: 'Rejected',
      priority: 'Medium',
      applicationEmail: email1.emailAddress,
      isFavorite: false,
      applicationFee: 75.0,
      ieltsRequired: true,
      ieltsOverallRequired: 6.5,
      myIeltsScore: 6.5,
      gpaRequired: 3.2,
      myGpa: 3.5,
      generalNotes: 'Rejected last year due to late module catalogue submission and lower score.',
      createdDate: '2025-05-01',
      lastUpdated: '2025-08-15',
    );

    // Application 3: University of Oxford (UK)
    final appId3 = uuid.v4();
    final app3 = ApplicationModel(
      id: appId3,
      universityName: 'University of Oxford',
      country: 'United Kingdom',
      city: 'Oxford',
      universityWebsite: 'https://www.ox.ac.uk',
      courseName: 'M.Sc. Advanced Computer Science',
      degreeLevel: "Master's",
      faculty: 'Department of Computer Science',
      studyMode: 'On Campus',
      duration: '1 Year',
      language: 'English',
      intake: 'Fall',
      semesterYear: '2026',
      applicationDeadline: DateTime(now.year, now.month, now.day + 8).toIso8601String().substring(0, 10), // 8 days: Urgent
      startOfApplications: DateTime(now.year, now.month - 2, 1).toIso8601String().substring(0, 10),
      scholarshipDeadline: DateTime(now.year, now.month, now.day + 8).toIso8601String().substring(0, 10),
      status: 'Interview',
      priority: 'High',
      applicationEmail: email2.emailAddress,
      isFavorite: true,
      applicationFee: 110.0,
      tuitionFee: 39500.0,
      livingCost: 15000.0,
      scholarshipAmount: 10000.0,
      ieltsRequired: true,
      ieltsOverallRequired: 7.5,
      ieltsListeningRequired: 7.0,
      ieltsReadingRequired: 7.0,
      ieltsWritingRequired: 7.0,
      ieltsSpeakingRequired: 7.0,
      myIeltsScore: 7.5,
      ieltsStatus: 'Requirement Met',
      gpaRequired: 3.7,
      myGpa: 3.75,
      sopRequired: true,
      cvRequired: true,
      recommendationRequired: true,
      interviewRequired: true,
      universityRating: 5.0,
      academicRating: 5.0,
      costRating: 2.5,
      locationRating: 4.8,
      careerRating: 5.0,
      studentLifeRating: 4.7,
      pros: 'World-renowned collegiate system, leading faculty in algorithms and verification.',
      cons: 'Extremely high tuition and living costs.',
      personalReview: 'Dream school. Technical interview scheduled for next Thursday.',
      createdDate: DateTime.now().toIso8601String().substring(0, 10),
      lastUpdated: DateTime.now().toIso8601String().substring(0, 10),
    );

    // Application 4: University of Melbourne (Australia)
    final appId4 = uuid.v4();
    final app4 = ApplicationModel(
      id: appId4,
      universityName: 'University of Melbourne',
      country: 'Australia',
      city: 'Melbourne',
      universityWebsite: 'https://www.unimelb.edu.au',
      courseName: 'Master of Information Technology',
      degreeLevel: "Master's",
      faculty: 'School of Computing and Information Systems',
      studyMode: 'On Campus',
      duration: '2 Years',
      language: 'English',
      intake: 'Spring',
      semesterYear: '2026',
      applicationDeadline: DateTime(now.year, now.month + 3, 20).toIso8601String().substring(0, 10),
      startOfApplications: DateTime(now.year, now.month - 1, 15).toIso8601String().substring(0, 10),
      status: 'Unconditional Offer',
      priority: 'High',
      applicationEmail: email1.emailAddress,
      isFavorite: true,
      applicationFee: 100.0,
      tuitionFee: 49000.0,
      livingCost: 22000.0,
      scholarshipAmount: 12000.0,
      ieltsRequired: true,
      ieltsOverallRequired: 6.5,
      myIeltsScore: 7.5,
      gpaRequired: 3.0,
      myGpa: 3.75,
      sopRequired: true,
      cvRequired: true,
      universityRating: 4.6,
      academicRating: 4.6,
      costRating: 3.2,
      locationRating: 5.0,
      careerRating: 4.7,
      studentLifeRating: 4.9,
      pros: 'Consistently ranked #1 in Australia, great post-study work visa rights.',
      cons: 'High tuition, long travel distance from home.',
      personalReview: 'Received unconditional offer with 25% Melbourne International Grant!',
      createdDate: DateTime.now().toIso8601String().substring(0, 10),
      lastUpdated: DateTime.now().toIso8601String().substring(0, 10),
    );

    // Application 5: University of Toronto (Canada)
    final appId5 = uuid.v4();
    final app5 = ApplicationModel(
      id: appId5,
      universityName: 'University of Toronto',
      country: 'Canada',
      city: 'Toronto',
      universityWebsite: 'https://www.utoronto.ca',
      courseName: 'Master of Science in Applied Computing',
      degreeLevel: "Master's",
      faculty: 'Department of Computer Science',
      studyMode: 'On Campus',
      duration: '1.5 Years',
      language: 'English',
      intake: 'Fall',
      semesterYear: '2026',
      applicationDeadline: DateTime(now.year, now.month, now.day + 2).toIso8601String().substring(0, 10), // 2 days: Critical
      startOfApplications: DateTime(now.year, now.month - 2, 1).toIso8601String().substring(0, 10),
      status: 'Applied',
      priority: 'Medium',
      applicationEmail: email1.emailAddress,
      isFavorite: false,
      applicationFee: 130.0,
      tuitionFee: 32000.0,
      livingCost: 18000.0,
      ieltsRequired: true,
      ieltsOverallRequired: 7.0,
      myIeltsScore: 7.5,
      gpaRequired: 3.3,
      myGpa: 3.75,
      sopRequired: true,
      cvRequired: true,
      recommendationRequired: true,
      universityRating: 4.7,
      academicRating: 4.8,
      costRating: 3.8,
      locationRating: 4.6,
      careerRating: 4.9,
      studentLifeRating: 4.3,
      pros: 'Includes 8-month paid industrial internship, vector institute AI hub.',
      cons: 'Very competitive admissions, cold winters.',
      personalReview: 'Application submitted. Waiting for confirmation email.',
      createdDate: DateTime.now().toIso8601String().substring(0, 10),
      lastUpdated: DateTime.now().toIso8601String().substring(0, 10),
    );

    // Application 6: ETH Zurich (Switzerland)
    final appId6 = uuid.v4();
    final app6 = ApplicationModel(
      id: appId6,
      universityName: 'ETH Zurich',
      country: 'Switzerland',
      city: 'Zurich',
      universityWebsite: 'https://ethz.ch',
      courseName: 'Master in Computer Science',
      degreeLevel: "Master's",
      faculty: 'Department of Computer Science',
      studyMode: 'On Campus',
      duration: '2 Years',
      language: 'English',
      intake: 'Fall',
      semesterYear: '2026',
      applicationDeadline: DateTime(now.year, now.month + 1, 20).toIso8601String().substring(0, 10),
      startOfApplications: DateTime(now.year, now.month - 1, 1).toIso8601String().substring(0, 10),
      status: 'Preparing',
      priority: 'High',
      applicationEmail: email1.emailAddress,
      isFavorite: true,
      applicationFee: 150.0,
      tuitionFee: 1500.0, // Low Swiss public university tuition
      livingCost: 24000.0,
      ieltsRequired: true,
      ieltsOverallRequired: 7.0,
      myIeltsScore: 7.5,
      gpaRequired: 3.6,
      myGpa: 3.75,
      sopRequired: true,
      cvRequired: true,
      recommendationRequired: true,
      universityRating: 4.9,
      academicRating: 5.0,
      costRating: 3.5,
      locationRating: 4.7,
      careerRating: 4.9,
      studentLifeRating: 4.5,
      pros: 'World #1 continental Europe university, cutting-edge labs, very low tuition.',
      cons: 'Living in Zurich is expensive, stringent admissions evaluation.',
      personalReview: 'Finalizing statement of purpose and syllabus comparison.',
      createdDate: DateTime.now().toIso8601String().substring(0, 10),
      lastUpdated: DateTime.now().toIso8601String().substring(0, 10),
    );

    // Application 7: National University of Singapore (Singapore)
    final appId7 = uuid.v4();
    final app7 = ApplicationModel(
      id: appId7,
      universityName: 'National University of Singapore',
      country: 'Singapore',
      city: 'Singapore',
      universityWebsite: 'https://nus.edu.sg',
      courseName: 'Master of Computing (Infocomm Security)',
      degreeLevel: "Master's",
      faculty: 'School of Computing',
      studyMode: 'On Campus',
      duration: '1.5 Years',
      language: 'English',
      intake: 'Fall',
      semesterYear: '2026',
      applicationDeadline: DateTime(now.year, now.month + 2, 28).toIso8601String().substring(0, 10),
      startOfApplications: DateTime(now.year, now.month - 1, 10).toIso8601String().substring(0, 10),
      status: 'Ready to Apply',
      priority: 'Medium',
      applicationEmail: email1.emailAddress,
      isFavorite: false,
      applicationFee: 100.0,
      tuitionFee: 38000.0,
      livingCost: 16000.0,
      ieltsRequired: true,
      ieltsOverallRequired: 6.5,
      myIeltsScore: 7.5,
      gpaRequired: 3.2,
      myGpa: 3.75,
      sopRequired: true,
      cvRequired: true,
      universityRating: 4.7,
      academicRating: 4.8,
      costRating: 3.6,
      locationRating: 4.8,
      careerRating: 4.8,
      studentLifeRating: 4.6,
      pros: 'Top ranked in Asia, vibrant international tech startup ecosystem.',
      cons: 'Hot tropical climate, rigorous pace.',
      personalReview: 'Checklist ready, awaiting final reference letter from professor.',
      createdDate: DateTime.now().toIso8601String().substring(0, 10),
      lastUpdated: DateTime.now().toIso8601String().substring(0, 10),
    );

    final apps = [app1, app2, app3, app4, app5, app6, app7];
    await repository.saveApplications(apps);

    // Add Status Histories
    final histories = <StatusHistoryModel>[
      StatusHistoryModel(
        id: uuid.v4(),
        applicationId: appId1,
        date: '2026-08-01',
        previousStatus: 'Researching',
        newStatus: 'Preparing',
        event: 'University Added',
        notes: 'Targeted M.Sc. Informatics program after verifying requirements.',
      ),
      StatusHistoryModel(
        id: uuid.v4(),
        applicationId: appId1,
        date: '2026-08-15',
        previousStatus: 'Preparing',
        newStatus: 'Documents Pending',
        event: 'uni-assist VPD Submitted',
        notes: 'Sent preliminary documentation to uni-assist.',
      ),
      StatusHistoryModel(
        id: uuid.v4(),
        applicationId: appId1,
        date: '2026-08-28',
        previousStatus: 'Documents Pending',
        newStatus: 'Applied',
        event: 'TUMonline Application Submitted',
        notes: 'Uploaded all certified copies and paid processing fee.',
      ),
      StatusHistoryModel(
        id: uuid.v4(),
        applicationId: appId1,
        date: '2026-09-02',
        previousStatus: 'Applied',
        newStatus: 'Under Review',
        event: 'Formal Check Passed',
        notes: 'Admissions committee commenced academic aptitude assessment.',
      ),
      StatusHistoryModel(
        id: uuid.v4(),
        applicationId: appId3,
        date: '2026-08-10',
        previousStatus: 'Researching',
        newStatus: 'Applied',
        event: 'Oxford Portal Submission',
        notes: 'Completed application fee payment and referee submissions.',
      ),
      StatusHistoryModel(
        id: uuid.v4(),
        applicationId: appId3,
        date: '2026-08-25',
        previousStatus: 'Applied',
        newStatus: 'Interview',
        event: 'Interview Invitation Received',
        notes: '30-minute academic interview scheduled with Dr. Michael Davies.',
      ),
      StatusHistoryModel(
        id: uuid.v4(),
        applicationId: appId4,
        date: '2026-07-15',
        previousStatus: 'Applied',
        newStatus: 'Under Review',
        event: 'Credentials Evaluation',
        notes: 'Assessment of international bachelor degree completed.',
      ),
      StatusHistoryModel(
        id: uuid.v4(),
        applicationId: appId4,
        date: '2026-08-20',
        previousStatus: 'Under Review',
        newStatus: 'Unconditional Offer',
        event: 'Offer of Admission Issued',
        notes: 'Full letter of offer received via email along with scholarship letter.',
      ),
    ];
    await repository.saveStatusHistory(histories);

    // Add Documents for TUM and Oxford
    final docs = <DocumentModel>[
      // TUM
      DocumentModel(id: uuid.v4(), applicationId: appId1, document: 'Valid Passport', completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId1, document: "Bachelor's Degree Certificate", completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId1, document: 'Official Transcripts', completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId1, document: 'IELTS Score Sheet (7.5)', completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId1, document: 'Curriculum Vitae (CV)', completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId1, document: 'uni-assist VPD Certificate', completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId1, document: 'Curriculum Analysis / Module Descriptions', completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId1, document: 'Statement of Purpose (SOP)', completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId1, document: 'German Blocked Account / Proof of Funds', completed: false, submitted: false, notes: 'Required for visa phase'),

      // Oxford
      DocumentModel(id: uuid.v4(), applicationId: appId3, document: 'Valid Passport', completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId3, document: 'Statement of Purpose', completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId3, document: 'Official Transcripts', completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId3, document: 'Academic Reference 1', completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId3, document: 'Academic Reference 2', completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId3, document: 'Academic Reference 3', completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId3, document: 'Research Sample / Portfolio', completed: true, submitted: true),
      DocumentModel(id: uuid.v4(), applicationId: appId3, document: 'Financial Declaration Form', completed: false, submitted: false),
    ];
    await repository.saveDocuments(docs);

    // Add Scholarships
    final scholarships = <ScholarshipModel>[
      ScholarshipModel(
        id: uuid.v4(),
        applicationId: '', // Independent Scholarship
        scholarshipName: 'Fulbright Foreign Student Fellowship',
        organization: 'Fulbright Commission / USEFP',
        amount: 25000.0,
        deadline: '2026-10-15',
        eligibility: 'Outstanding academic record, leadership potential, GRE required',
        status: 'Preparing',
        notes: 'Independent national competition covering full tuition, living stipend, and airfare.',
      ),
      ScholarshipModel(
        id: uuid.v4(),
        applicationId: appId1,
        scholarshipName: 'DAAD Helmut-Schmidt Programme / Study Scholarship',
        organization: 'DAAD Germany',
        amount: 3600.0,
        deadline: '2026-10-31',
        eligibility: 'Graduates with outstanding academic performance',
        status: 'Applied',
        notes: 'Covers monthly allowance and health insurance support.',
      ),
      ScholarshipModel(
        id: uuid.v4(),
        applicationId: appId3,
        scholarshipName: 'Clarendon Fund Scholarship',
        organization: 'University of Oxford',
        amount: 10000.0,
        deadline: '2026-09-14',
        eligibility: 'Automatically considered with course application',
        status: 'Under Review',
        notes: 'Prestigious full/partial tuition award.',
      ),
      ScholarshipModel(
        id: uuid.v4(),
        applicationId: appId4,
        scholarshipName: 'Melbourne International Undergraduate/Graduate Scholarship',
        organization: 'University of Melbourne',
        amount: 12000.0,
        deadline: '2026-11-01',
        eligibility: 'High academic merit in previous studies',
        status: 'Awarded',
        notes: '25% fee remission granted in the admission letter.',
      ),
    ];
    await repository.saveScholarships(scholarships);

    // Add Contacts
    final contacts = <ContactModel>[
      ContactModel(
        id: uuid.v4(),
        applicationId: appId1,
        department: 'TUM Department of Informatics Admissions',
        contactPerson: 'Admissions Office',
        email: 'studium@in.tum.de',
        phone: '+49 89 289 17500',
        notes: 'Response time typically 3 business days. Reference applicant number in subject.',
      ),
      ContactModel(
        id: uuid.v4(),
        applicationId: appId3,
        department: 'Oxford Graduate Admissions',
        contactPerson: 'Sarah Jenkins (Faculty Coordinator)',
        email: 'graduate.admissions@cs.ox.ac.uk',
        phone: '+44 1865 273838',
        notes: 'Contact for interview technical arrangements.',
      ),
      ContactModel(
        id: uuid.v4(),
        applicationId: appId4,
        department: 'Stop 1 Melbourne',
        contactPerson: 'International Admissions Support',
        email: 'international@unimelb.edu.au',
        phone: '+61 3 9035 5511',
        notes: 'For visa letter of confirmation and offer acceptance procedures.',
      ),
    ];
    await repository.saveContacts(contacts);
  }
}
